import type { Metadata } from 'next'

import Header from './_components/navigation/header'
import Footer from './_components/navigation/footer'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Car hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="relative">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
